-- Generated by hyprmoncfg.
-- TODO: This module is not loaded by hyprland.lua while hyprmoncfg writes
-- ~/.config/hypr/monitors.lua directly. Remove this tracked copy once the
-- generated-monitor workflow is settled.

hl.monitor({
  output = "desc:LG Electronics LG ULTRAFINE 206NTBK14189",
  mode = "3840x2160@60.00",
  position = "-2560x0",
  scale = 1.5,
  bitdepth = 16,
  cm = "dcip3",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:California Institute of Technology 0x1411",
  disabled = true,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:California Institute of Technology 0x1411", default = true, persistent = true })
hl.workspace_rule({ workspace = "1", monitor = "desc:LG Electronics LG ULTRAFINE 206NTBK14189", default = true, persistent = true })
