font_family JetBrainsMono Nerd Font
font_size 12

adjust_line_height 110%
adjust_column_width 0
symbol_map U+E000-U+F8FF Symbols Nerd Font Mono

macos_option_as_alt yes
copy_on_select clipboard
strip_trailing_spaces smart
enable_audio_bell no
confirm_os_window_close 0

background_opacity 0.8
window_padding_width 8
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal

foreground #d4d4d4
background #1a1a1a
selection_foreground #d4d4d4
selection_background #4d4d4d
cursor #d4d4d4
cursor_text_color #1a1a1a
cursor_blink_interval 0
url_color #6d8bb5

active_tab_foreground #1a1a1a
active_tab_background #6b6b6b
inactive_tab_foreground #aaaaaa
inactive_tab_background #2e2e2e
tab_bar_background #1a1a1a

active_border_color #6b6b6b
inactive_border_color #2e2e2e
bell_border_color #b5ad6d

color0 #1a1a1a
color1 #b56d6d
color2 #7a9c7a
color3 #b5ad6d
color4 #6d8bb5
color5 #906db5
color6 #6d9cb5
color7 #d4d4d4
color8 #6b6b6b
color9 #b56d6d
color10 #7a9c7a
color11 #b5ad6d
color12 #6d8bb5
color13 #906db5
color14 #6d9cb5
color15 #aaaaaa
