font_family FiraCode Nerd Font
font_size 12

adjust_line_height 110%
adjust_column_width 0
symbol_map U+E000-U+F8FF Symbols Nerd Font Mono

macos_option_as_alt yes
copy_on_select clipboard
strip_trailing_spaces smart
enable_audio_bell no
confirm_os_window_close 0

window_padding_width 8
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal

foreground #D8DEE9
background #2E3440
selection_foreground #2E3440
selection_background #D8DEE9
cursor #D8DEE9
cursor_text_color #2E3440
url_color #88C0D0

active_tab_foreground #2E3440
active_tab_background #88C0D0
inactive_tab_foreground #D8DEE9
inactive_tab_background #3B4252
tab_bar_background #2E3440

active_border_color #88C0D0
inactive_border_color #4C566A
bell_border_color #EBCB8B

color0 #3B4252
color1 #BF616A
color2 #A3BE8C
color3 #EBCB8B
color4 #81A1C1
color5 #B48EAD
color6 #88C0D0
color7 #E5E9F0
color8 #4C566A
color9 #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #8FBCBB
color15 #ECEFF4
