preload = /home/minhuy/dotfiles/wallpapers/dr15.jpg
wallpaper {
    monitor = eDP-1
    path = /home/minhuy/dotfiles/wallpapers/dr15.jpg
}

wallpaper {
    monitor = 
    path = /home/minhuy/dotfiles/wallpapers/dr15.jpg
}
